"""Seed the database with sample certificate data for demonstration."""
from datetime import datetime, timezone, timedelta
from sqlalchemy.orm import Session
from app.models.certificate import Certificate, CertificateType, CertificateStatus


SAMPLE_CERTIFICATES = [
    # Database Server Certificates
    {
        "name": "Oracle DB Production",
        "hostname": "oracle-prod.example.com",
        "port": 2484,
        "certificate_type": CertificateType.DATABASE_SERVER,
        "environment": "Production",
        "owner_team": "DBA Team",
        "owner_email": "dba-team@example.com",
        "description": "Oracle production database SSL certificate",
        "status": CertificateStatus.VALID,
        "issuer": "CN=DigiCert SHA2 Secure Server CA",
        "subject": "CN=oracle-prod.example.com",
        "days_until_expiry": 245,
        "expiry_date": datetime.now(timezone.utc) + timedelta(days=245),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=120),
    },
    {
        "name": "PostgreSQL Staging",
        "hostname": "postgres-staging.example.com",
        "port": 5432,
        "certificate_type": CertificateType.DATABASE_SERVER,
        "environment": "Staging",
        "owner_team": "DBA Team",
        "owner_email": "dba-team@example.com",
        "description": "PostgreSQL staging database SSL certificate",
        "status": CertificateStatus.EXPIRING_SOON,
        "issuer": "CN=Let's Encrypt Authority X3",
        "subject": "CN=postgres-staging.example.com",
        "days_until_expiry": 22,
        "expiry_date": datetime.now(timezone.utc) + timedelta(days=22),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=343),
    },
    {
        "name": "MySQL DR Instance",
        "hostname": "mysql-dr.example.com",
        "port": 3306,
        "certificate_type": CertificateType.DATABASE_SERVER,
        "environment": "DR",
        "owner_team": "DBA Team",
        "owner_email": "dba-team@example.com",
        "description": "MySQL disaster recovery database SSL certificate",
        "status": CertificateStatus.VALID,
        "issuer": "CN=GlobalSign RSA OV SSL CA",
        "subject": "CN=mysql-dr.example.com",
        "days_until_expiry": 180,
        "expiry_date": datetime.now(timezone.utc) + timedelta(days=180),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=185),
    },
    # Okta Certificates
    {
        "name": "Okta SSO Production",
        "hostname": "company.okta.com",
        "port": 443,
        "certificate_type": CertificateType.OKTA,
        "environment": "Production",
        "owner_team": "Identity & Access Team",
        "owner_email": "iam-team@example.com",
        "description": "Okta SSO production SAML certificate",
        "status": CertificateStatus.VALID,
        "issuer": "CN=DigiCert Global Root G2",
        "subject": "CN=company.okta.com",
        "days_until_expiry": 320,
        "expiry_date": datetime.now(timezone.utc) + timedelta(days=320),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=45),
    },
    {
        "name": "Okta API Token Cert",
        "hostname": "api.okta.com",
        "port": 443,
        "certificate_type": CertificateType.OKTA,
        "environment": "Production",
        "owner_team": "Identity & Access Team",
        "owner_email": "iam-team@example.com",
        "description": "Okta API integration certificate",
        "status": CertificateStatus.CRITICAL,
        "issuer": "CN=DigiCert SHA2 Extended Validation Server CA",
        "subject": "CN=api.okta.com",
        "days_until_expiry": 5,
        "expiry_date": datetime.now(timezone.utc) + timedelta(days=5),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=360),
    },
    # Load Balancer Certificates
    {
        "name": "Main LB - Web App",
        "hostname": "app.example.com",
        "port": 443,
        "certificate_type": CertificateType.LOAD_BALANCER,
        "environment": "Production",
        "owner_team": "Platform Engineering",
        "owner_email": "platform@example.com",
        "description": "Main load balancer SSL certificate for web application",
        "status": CertificateStatus.VALID,
        "issuer": "CN=Amazon RSA 2048 M02",
        "subject": "CN=app.example.com",
        "days_until_expiry": 290,
        "expiry_date": datetime.now(timezone.utc) + timedelta(days=290),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=75),
    },
    {
        "name": "API Gateway LB",
        "hostname": "api.example.com",
        "port": 443,
        "certificate_type": CertificateType.LOAD_BALANCER,
        "environment": "Production",
        "owner_team": "Platform Engineering",
        "owner_email": "platform@example.com",
        "description": "API gateway load balancer certificate",
        "status": CertificateStatus.EXPIRING_SOON,
        "issuer": "CN=Cloudflare Inc ECC CA-3",
        "subject": "CN=api.example.com",
        "days_until_expiry": 15,
        "expiry_date": datetime.now(timezone.utc) + timedelta(days=15),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=350),
    },
    {
        "name": "Internal LB - Microservices",
        "hostname": "internal-lb.example.com",
        "port": 443,
        "certificate_type": CertificateType.LOAD_BALANCER,
        "environment": "Production",
        "owner_team": "Platform Engineering",
        "owner_email": "platform@example.com",
        "description": "Internal load balancer for microservices mesh",
        "status": CertificateStatus.VALID,
        "issuer": "CN=Internal CA",
        "subject": "CN=internal-lb.example.com",
        "days_until_expiry": 200,
        "expiry_date": datetime.now(timezone.utc) + timedelta(days=200),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=165),
    },
    # Java App Certificates
    {
        "name": "HRMS Spring Boot Keystore",
        "hostname": "hrms.example.com",
        "port": 8443,
        "certificate_type": CertificateType.JAVA_APP,
        "environment": "Production",
        "owner_team": "HR Applications",
        "owner_email": "hr-apps@example.com",
        "description": "Java keystore certificate for HRMS Spring Boot application",
        "status": CertificateStatus.VALID,
        "issuer": "CN=Sectigo RSA Domain Validation Secure Server CA",
        "subject": "CN=hrms.example.com",
        "days_until_expiry": 150,
        "expiry_date": datetime.now(timezone.utc) + timedelta(days=150),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=215),
    },
    {
        "name": "Payment Service JKS",
        "hostname": "payment.example.com",
        "port": 8443,
        "certificate_type": CertificateType.JAVA_APP,
        "environment": "Production",
        "owner_team": "Payments Team",
        "owner_email": "payments@example.com",
        "description": "Java keystore for payment processing service",
        "status": CertificateStatus.EXPIRED,
        "issuer": "CN=GeoTrust TLS RSA CA G1",
        "subject": "CN=payment.example.com",
        "days_until_expiry": -3,
        "expiry_date": datetime.now(timezone.utc) - timedelta(days=3),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=368),
    },
    {
        "name": "Reporting Service Truststore",
        "hostname": "reports.example.com",
        "port": 8443,
        "certificate_type": CertificateType.JAVA_APP,
        "environment": "Staging",
        "owner_team": "Analytics Team",
        "owner_email": "analytics@example.com",
        "description": "Java truststore certificate for reporting service",
        "status": CertificateStatus.VALID,
        "issuer": "CN=Comodo RSA Domain Validation Secure Server CA",
        "subject": "CN=reports.example.com",
        "days_until_expiry": 88,
        "expiry_date": datetime.now(timezone.utc) + timedelta(days=88),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=277),
    },
    # Third Party Certificates
    {
        "name": "Stripe Payment Gateway",
        "hostname": "api.stripe.com",
        "port": 443,
        "certificate_type": CertificateType.THIRD_PARTY,
        "environment": "Production",
        "owner_team": "Payments Team",
        "owner_email": "payments@example.com",
        "description": "Stripe payment gateway API SSL certificate",
        "status": CertificateStatus.VALID,
        "issuer": "CN=DigiCert SHA2 Extended Validation Server CA",
        "subject": "CN=api.stripe.com",
        "days_until_expiry": 310,
        "expiry_date": datetime.now(timezone.utc) + timedelta(days=310),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=55),
    },
    {
        "name": "Twilio SMS Service",
        "hostname": "api.twilio.com",
        "port": 443,
        "certificate_type": CertificateType.THIRD_PARTY,
        "environment": "Production",
        "owner_team": "Communications Team",
        "owner_email": "comms@example.com",
        "description": "Twilio SMS service API certificate",
        "status": CertificateStatus.VALID,
        "issuer": "CN=Amazon RSA 2048 M01",
        "subject": "CN=api.twilio.com",
        "days_until_expiry": 275,
        "expiry_date": datetime.now(timezone.utc) + timedelta(days=275),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=90),
    },
    {
        "name": "SendGrid Email Service",
        "hostname": "api.sendgrid.com",
        "port": 443,
        "certificate_type": CertificateType.THIRD_PARTY,
        "environment": "Production",
        "owner_team": "Communications Team",
        "owner_email": "comms@example.com",
        "description": "SendGrid email API certificate",
        "status": CertificateStatus.EXPIRING_SOON,
        "issuer": "CN=Cloudflare Inc ECC CA-3",
        "subject": "CN=api.sendgrid.com",
        "days_until_expiry": 28,
        "expiry_date": datetime.now(timezone.utc) + timedelta(days=28),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=337),
    },
    {
        "name": "Salesforce CRM Integration",
        "hostname": "login.salesforce.com",
        "port": 443,
        "certificate_type": CertificateType.THIRD_PARTY,
        "environment": "Production",
        "owner_team": "CRM Team",
        "owner_email": "crm@example.com",
        "description": "Salesforce CRM API integration certificate",
        "status": CertificateStatus.VALID,
        "issuer": "CN=DigiCert SHA2 Secure Server CA",
        "subject": "CN=login.salesforce.com",
        "days_until_expiry": 195,
        "expiry_date": datetime.now(timezone.utc) + timedelta(days=195),
        "issued_date": datetime.now(timezone.utc) - timedelta(days=170),
    },
]


def seed_database(db: Session):
    """Insert sample certificates if the database is empty."""
    existing = db.query(Certificate).count()
    if existing > 0:
        return  # Already seeded

    for cert_data in SAMPLE_CERTIFICATES:
        cert = Certificate(**cert_data)
        cert.last_checked = datetime.now(timezone.utc)
        cert.serial_number = f"{hash(cert_data['name']) & 0xFFFFFFFFFFFF:012x}"
        db.add(cert)

    db.commit()
