/**
 * login test
 *
 * Auto-converted from UFT/QTP VBScript to Playwright TypeScript
 * Generated by UFT-to-Playwright Converter
 *
 * TODO: Review and update selectors for your application
 * TODO: Replace hardcoded test data with fixtures or environment variables
 * TODO: Add proper assertions where TODO comments exist
 */

import { test, expect } from '@playwright/test';

import { LoginPage } from './pages/login.page';
import { DashboardPage } from './pages/dashboard.page';

test.describe('login test', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('http://localhost:3000');
  });

  test('login-test', async ({ page }) => {
    // UFT Line 9: SystemUtil.Run "http://localhost:3000"
    // TODO: Low confidence mapping (70%): SystemUtil.Run
    // TODO: Note: SystemUtil.Run usually opens a URL. Adjust if it launches a desktop app.
    await page.goto('http://localhost:3000')
    // UFT Line 10: Wait 3
    // TODO: Note: Consider replacing hard waits with waitForSelector or waitForLoadState.
    await page.waitForTimeout(3 * 1000)
    // UFT Line 13: Browser("HRMS").Page("Login").WebEdit("txt_username").Set "admin@company.com"
    await page.locator('#txt_username').fill('admin@company.com')
    // UFT Line 14: Browser("HRMS").Page("Login").WebEdit("txt_password").SetSecure "5a4b3c2d1e"
    // TODO: Note: SetSecure uses encrypted values in UFT. Replace with actual test credential.
    await page.locator('#txt_password').fill('5a4b3c2d1e')
    // UFT Line 15: Browser("HRMS").Page("Login").WebButton("btn_login").Click
    await page.locator('#btn_login').click()
    // UFT Line 18: Browser("HRMS").Page("Dashboard").Sync
    await page.waitForLoadState('networkidle')
    // UNMAPPED: userName = Browser("HRMS").Page("Dashboard").WebElement("welcome_msg").GetROProperty("innertext")
    // UFT Line 29: userName = Browser("HRMS").Page("Dashboard").WebElement("welcome_msg").GetROProperty("innertext")
    // TODO: Unsupported object type: GetROProperty
    // TODO: Manual conversion needed - Unsupported object type: GetROProperty
    // Original: userName = Browser("HRMS").Page("Dashboard").WebElement("welcome_msg").GetROProperty("innertext")
    // UFT Line 38: Browser("HRMS").Page("Dashboard").Link("lnk_logout").Click
    await page.locator('#lnk_logout').click()
    // UFT Line 39: Wait 2
    // TODO: Note: Consider replacing hard waits with waitForSelector or waitForLoadState.
    await page.waitForTimeout(2 * 1000)
    // UFT Line 49: Browser("HRMS").Page("Login").WebEdit("txt_username").Set "invalid@company.com"
    await page.locator('#txt_username').fill('invalid@company.com')
    // UFT Line 50: Browser("HRMS").Page("Login").WebEdit("txt_password").Set "wrong_password"
    await page.locator('#txt_password').fill('wrong_password')
    // UFT Line 51: Browser("HRMS").Page("Login").WebButton("btn_login").Click
    await page.locator('#btn_login').click()
    // UFT Line 52: Wait 2
    // TODO: Note: Consider replacing hard waits with waitForSelector or waitForLoadState.
    await page.waitForTimeout(2 * 1000)
    // UFT Line 62: Browser("HRMS").Close
    await page.close()

    // Assertions
    // UFT Line 21: If Browser("HRMS").Page("Dashboard").WebElement("welcome_msg").Exist(10) Then
    await page.locator('#welcome_msg').isVisible()
    // UFT Line 22: Reporter.ReportEvent micPass, "Login Test", "Login successful - Dashboard loaded"
    // TODO: Low confidence mapping (70%): Reporter.ReportEvent
    // TODO: Note: Reporter events can be replaced with test.info() or expect() assertions.
    // Assertion: Login Test - Login successful - Dashboard loaded
    console.log('[micPass] : ')
    // UFT Line 24: Reporter.ReportEvent micFail, "Login Test", "Login failed - Dashboard not loaded"
    // TODO: Low confidence mapping (70%): Reporter.ReportEvent
    // TODO: Note: Reporter events can be replaced with test.info() or expect() assertions.
    // Assertion: Login Test - Login failed - Dashboard not loaded
    console.log('[micFail] : ')
    // UFT Line 32: Reporter.ReportEvent micPass, "User Name", "User name displayed correctly: " & userName
    // TODO: Low confidence mapping (70%): Reporter.ReportEvent
    // TODO: Note: Reporter events can be replaced with test.info() or expect() assertions.
    // Assertion: User Name - User name displayed correctly:
    console.log('[micPass] : ')
    // UFT Line 34: Reporter.ReportEvent micFail, "User Name", "User name not found. Got: " & userName
    // TODO: Low confidence mapping (70%): Reporter.ReportEvent
    // TODO: Note: Reporter events can be replaced with test.info() or expect() assertions.
    // Assertion: User Name - User name not found. Got:
    console.log('[micFail] : ')
    // UFT Line 42: If Browser("HRMS").Page("Login").WebEdit("txt_username").Exist(5) Then
    await page.locator('#txt_username').isVisible()
    // UFT Line 43: Reporter.ReportEvent micPass, "Logout Test", "Logout successful - Login page displayed"
    // TODO: Low confidence mapping (70%): Reporter.ReportEvent
    // TODO: Note: Reporter events can be replaced with test.info() or expect() assertions.
    // Assertion: Logout Test - Logout successful - Login page displayed
    console.log('[micPass] : ')
    // UFT Line 45: Reporter.ReportEvent micFail, "Logout Test", "Logout failed"
    // TODO: Low confidence mapping (70%): Reporter.ReportEvent
    // TODO: Note: Reporter events can be replaced with test.info() or expect() assertions.
    // Assertion: Logout Test - Logout failed
    console.log('[micFail] : ')
    // UFT Line 55: If Browser("HRMS").Page("Login").WebElement("error_msg").Exist(5) Then
    await page.locator('#error_msg').isVisible()
    // UFT Line 56: Reporter.ReportEvent micPass, "Invalid Login", "Error message displayed for invalid credentials"
    // TODO: Low confidence mapping (70%): Reporter.ReportEvent
    // TODO: Note: Reporter events can be replaced with test.info() or expect() assertions.
    // Assertion: Invalid Login - Error message displayed for invalid credentials
    console.log('[micPass] : ')
    // UFT Line 58: Reporter.ReportEvent micFail, "Invalid Login", "Error message not displayed"
    // TODO: Low confidence mapping (70%): Reporter.ReportEvent
    // TODO: Note: Reporter events can be replaced with test.info() or expect() assertions.
    // Assertion: Invalid Login - Error message not displayed
    console.log('[micFail] : ')
  });
});
