/**
 * Playwright Generator - Generates Playwright TypeScript test files from
 * transformed test structures.
 *
 * Produces:
 * - Test spec files (.spec.ts)
 * - Page Object files
 * - Playwright configuration
 * - Test data fixtures
 */

import {
  PlaywrightTestFile,
  PlaywrightAction,
  PageObject,
  ConversionConfig,
} from '../models/types';


export class PlaywrightGenerator {
  constructor(private config: ConversionConfig) {}

  /**
   * Generate a complete Playwright test file as a string.
   */
  generateTestFile(testFile: PlaywrightTestFile): string {
    const sections: string[] = [];

    // File header
    sections.push(this.generateFileHeader(testFile));

    // Imports
    sections.push(this.generateImports(testFile));

    // Page Object imports (if applicable)
    if (testFile.pageObjectRefs.length > 0 && this.config.generatePageObjects) {
      sections.push(this.generatePageObjectImports(testFile));
    }

    // Test describe block
    sections.push(this.generateTestDescribe(testFile));

    return sections.filter(Boolean).join('\n\n') + '\n';
  }

  /**
   * Generate the file header comment.
   */
  private generateFileHeader(testFile: PlaywrightTestFile): string {
    return [
      '/**',
      ` * ${testFile.testName}`,
      ' *',
      ' * Auto-converted from UFT/QTP VBScript to Playwright TypeScript',
      ` * Generated by UFT-to-Playwright Converter`,
      ' *',
      ' * TODO: Review and update selectors for your application',
      ' * TODO: Replace hardcoded test data with fixtures or environment variables',
      ' * TODO: Add proper assertions where TODO comments exist',
      ' */',
    ].join('\n');
  }

  /**
   * Generate import statements.
   */
  private generateImports(testFile: PlaywrightTestFile): string {
    const imports = new Set<string>();

    for (const imp of testFile.imports) {
      // Normalize: ensure trailing semicolon
      const normalized = imp.endsWith(';') ? imp : imp + ';';
      imports.add(normalized);
    }

    // Ensure base Playwright import exists
    imports.add("import { test, expect } from '@playwright/test';");

    return Array.from(imports).join('\n');
  }

  /**
   * Generate page object import statements.
   */
  private generatePageObjectImports(testFile: PlaywrightTestFile): string {
    return testFile.pageObjectRefs
      .map(ref => {
        const className = this.toPascalCase(ref) + 'Page';
        const fileName = this.toKebabCase(ref) + '.page';
        return `import { ${className} } from './pages/${fileName}';`;
      })
      .join('\n');
  }

  /**
   * Generate the test.describe block with all test cases.
   */
  private generateTestDescribe(testFile: PlaywrightTestFile): string {
    const lines: string[] = [];

    lines.push(`test.describe('${this.escapeString(testFile.testName)}', () => {`);

    // beforeEach hook
    if (testFile.beforeEach.length > 0) {
      lines.push('  test.beforeEach(async ({ page }) => {');
      for (const hook of testFile.beforeEach) {
        lines.push(`    ${hook}`);
      }
      lines.push('  });');
      lines.push('');
    }

    // Test blocks
    for (let i = 0; i < testFile.testBlocks.length; i++) {
      const block = testFile.testBlocks[i];
      if (i > 0) lines.push('');

      lines.push(`  test('${this.escapeString(block.name)}', async ({ page }) => {`);

      // Actions
      for (const action of block.actions) {
        const actionLines = this.generateAction(action);
        for (const line of actionLines) {
          lines.push(`    ${line}`);
        }
      }

      // Assertions
      if (block.assertions.length > 0) {
        lines.push('');
        lines.push('    // Assertions');
        for (const assertion of block.assertions) {
          const assertionLines = this.generateAction(assertion);
          for (const line of assertionLines) {
            lines.push(`    ${line}`);
          }
        }
      }

      lines.push('  });');
    }

    // afterEach hook
    if (testFile.afterEach.length > 0) {
      lines.push('');
      lines.push('  test.afterEach(async ({ page }) => {');
      for (const hook of testFile.afterEach) {
        lines.push(`    ${hook}`);
      }
      lines.push('  });');
    }

    lines.push('});');

    return lines.join('\n');
  }

  /**
   * Generate code lines for a single Playwright action.
   */
  private generateAction(action: PlaywrightAction): string[] {
    const lines: string[] = [];

    // Add comments
    for (const comment of action.comments) {
      lines.push(comment);
    }

    // Add warnings as TODO comments
    for (const warning of action.warnings) {
      lines.push(`// TODO: ${warning}`);
    }

    // Add the action code
    const codeLines = action.code.split('\n');
    for (const codeLine of codeLines) {
      lines.push(codeLine);
    }

    return lines;
  }

  /**
   * Generate a Page Object class file.
   */
  generatePageObject(pageObject: PageObject): string {
    const lines: string[] = [];

    // Header
    lines.push('/**');
    lines.push(` * Page Object: ${pageObject.className}`);
    lines.push(' * Auto-generated from UFT Object Repository');
    lines.push(' */');
    lines.push('');

    // Imports
    lines.push("import { Page, Locator } from '@playwright/test';");
    for (const imp of pageObject.imports) {
      lines.push(imp);
    }
    lines.push('');

    // Class definition
    lines.push(`export class ${pageObject.className} {`);

    // Selector constants
    lines.push('  // Selectors');
    for (const sel of pageObject.selectors) {
      const comment = sel.originalUFTObject
        ? ` // UFT: ${sel.originalUFTObject}`
        : '';
      lines.push(`  private readonly ${sel.name} = '${sel.selector}';${comment}`);
    }
    lines.push('');

    // Constructor
    lines.push('  constructor(private readonly page: Page) {}');
    lines.push('');

    // URL navigation (if applicable)
    if (pageObject.url) {
      lines.push('  async navigate(): Promise<void> {');
      lines.push(`    await this.page.goto('${pageObject.url}');`);
      lines.push('  }');
      lines.push('');
    }

    // Locator getters
    lines.push('  // Locators');
    for (const sel of pageObject.selectors) {
      const methodName = `get${this.toPascalCase(sel.name)}`;
      lines.push(`  ${methodName}(): Locator {`);
      lines.push(`    return this.page.locator(this.${sel.name});`);
      lines.push('  }');
      lines.push('');
    }

    // Custom methods
    if (pageObject.methods.length > 0) {
      lines.push('  // Actions');
      for (const method of pageObject.methods) {
        const params = method.parameters
          .map(p => `${p.name}: ${p.type}`)
          .join(', ');
        const asyncPrefix = method.isAsync ? 'async ' : '';

        lines.push(`  ${asyncPrefix}${method.name}(${params}): ${method.returnType} {`);
        const bodyLines = method.body.split('\n');
        for (const bodyLine of bodyLines) {
          lines.push(`    ${bodyLine}`);
        }
        lines.push('  }');
        lines.push('');
      }
    }

    lines.push('}');

    return lines.join('\n') + '\n';
  }

  /**
   * Generate Playwright configuration file.
   */
  generateConfig(): string {
    const browsers = this.config.browsers.length > 0
      ? this.config.browsers
      : ['chromium'];

    const projects = browsers.map(browser => {
      const browserName = browser === 'chrome' ? 'chromium' : browser;
      return `    {
      name: '${browserName}',
      use: { ...devices['Desktop ${this.capitalize(browserName)}'] },
    }`;
    });

    return `import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright configuration - auto-generated for UFT migration.
 * See https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  testDir: './tests',
  fullyParallel: ${this.config.parallel},
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? ${this.config.retries} : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: '${this.config.reportFormat}',

  use: {
    baseURL: '${this.config.baseUrl || 'http://localhost:3000'}',
    trace: '${this.config.traceOnFailure ? 'on-first-retry' : 'off'}',
    screenshot: '${this.config.screenshotOnFailure ? 'only-on-failure' : 'off'}',
    video: '${this.config.videoOnFailure ? 'on-first-retry' : 'off'}',
    actionTimeout: ${this.config.timeout},
  },

  projects: [
${projects.join(',\n')}
  ],
});
`;
  }

  /**
   * Generate a fixture file for shared test data.
   */
  generateFixture(dataColumns: Map<string, string[]>): string {
    const lines: string[] = [];

    lines.push("import { test as base } from '@playwright/test';");
    lines.push('');
    lines.push('// Test data fixture - migrated from UFT DataTable');
    lines.push('// Update with actual test data values');
    lines.push('');

    lines.push('interface TestData {');
    for (const [sheet, columns] of dataColumns) {
      lines.push(`  ${this.toCamelCase(sheet)}: {`);
      for (const col of columns) {
        lines.push(`    ${this.toCamelCase(col)}: string;`);
      }
      lines.push('  };');
    }
    lines.push('}');
    lines.push('');

    lines.push('export const test = base.extend<{ testData: TestData }>({');
    lines.push('  testData: async ({}, use) => {');
    lines.push('    await use({');
    for (const [sheet, columns] of dataColumns) {
      lines.push(`      ${this.toCamelCase(sheet)}: {`);
      for (const col of columns) {
        lines.push(`        ${this.toCamelCase(col)}: 'TODO: Add test data',`);
      }
      lines.push('      },');
    }
    lines.push('    });');
    lines.push('  },');
    lines.push('});');
    lines.push('');
    lines.push("export { expect } from '@playwright/test';");

    return lines.join('\n') + '\n';
  }

  // ==================== String utilities ====================

  private escapeString(str: string): string {
    return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  }

  private toPascalCase(str: string): string {
    return str
      .replace(/[^a-zA-Z0-9]+(.)/g, (_, char) => char.toUpperCase())
      .replace(/^./, char => char.toUpperCase());
  }

  private toCamelCase(str: string): string {
    return str
      .replace(/[^a-zA-Z0-9]+(.)/g, (_, char) => char.toUpperCase())
      .replace(/^[A-Z]/, char => char.toLowerCase());
  }

  private toKebabCase(str: string): string {
    return str
      .replace(/([a-z])([A-Z])/g, '$1-$2')
      .replace(/[^a-zA-Z0-9]+/g, '-')
      .toLowerCase();
  }

  private capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}
